// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	aggregates "github.com/jcleira/coding-challenge/internal/domain/aggregates"

	mock "github.com/stretchr/testify/mock"
)

// SolanaSender is an autogenerated mock type for the SolanaSender type
type SolanaSender struct {
	mock.Mock
}

// SendTransaction provides a mock function with given fields: _a0, _a1, _a2
func (_m *SolanaSender) SendTransaction(_a0 context.Context, _a1 aggregates.Transaction, _a2 aggregates.Wallet) (string, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, aggregates.Transaction, aggregates.Wallet) (string, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, aggregates.Transaction, aggregates.Wallet) string); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, aggregates.Transaction, aggregates.Wallet) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSolanaSender creates a new instance of SolanaSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSolanaSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *SolanaSender {
	mock := &SolanaSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
