// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// SolanaBalanceGetter is an autogenerated mock type for the SolanaBalanceGetter type
type SolanaBalanceGetter struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx, publicKey
func (_m *SolanaBalanceGetter) GetBalance(ctx context.Context, publicKey string) (uint64, error) {
	ret := _m.Called(ctx, publicKey)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (uint64, error)); ok {
		return rf(ctx, publicKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) uint64); ok {
		r0 = rf(ctx, publicKey)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, publicKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSolanaBalanceGetter creates a new instance of SolanaBalanceGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSolanaBalanceGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *SolanaBalanceGetter {
	mock := &SolanaBalanceGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
