// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	aggregates "github.com/jcleira/coding-challenge/internal/domain/aggregates"

	mock "github.com/stretchr/testify/mock"
)

// TransactionsSender is an autogenerated mock type for the TransactionsSender type
type TransactionsSender struct {
	mock.Mock
}

// SendTransaction provides a mock function with given fields: _a0, _a1
func (_m *TransactionsSender) SendTransaction(_a0 context.Context, _a1 aggregates.Transaction) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, aggregates.Transaction) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, aggregates.Transaction) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, aggregates.Transaction) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTransactionsSender creates a new instance of TransactionsSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTransactionsSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *TransactionsSender {
	mock := &TransactionsSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
