// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WalletBalanceGetter is an autogenerated mock type for the WalletBalanceGetter type
type WalletBalanceGetter struct {
	mock.Mock
}

// GetBalance provides a mock function with given fields: ctx, pubKey
func (_m *WalletBalanceGetter) GetBalance(ctx context.Context, pubKey string) (string, error) {
	ret := _m.Called(ctx, pubKey)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, pubKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, pubKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, pubKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWalletBalanceGetter creates a new instance of WalletBalanceGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletBalanceGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletBalanceGetter {
	mock := &WalletBalanceGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
