// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	aggregates "github.com/jcleira/coding-challenge/internal/domain/aggregates"
	mock "github.com/stretchr/testify/mock"
)

// WalletCreator is an autogenerated mock type for the WalletCreator type
type WalletCreator struct {
	mock.Mock
}

// CreateWallet provides a mock function with given fields:
func (_m *WalletCreator) CreateWallet() (aggregates.Wallet, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 aggregates.Wallet
	var r1 error
	if rf, ok := ret.Get(0).(func() (aggregates.Wallet, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() aggregates.Wallet); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(aggregates.Wallet)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewWalletCreator creates a new instance of WalletCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletCreator(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletCreator {
	mock := &WalletCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
